### ISSUE TITLE
prédiction des notes

### ISSUE THREAD

**Issue by hieros69** [minj/foxtrick#1515] opened 2017-07-14 10:38 UTC
bonjour,

les prédictions de notes ne fonctionnent plus sur foxtrick. Tout est noté inexistant.

Cordialement

**Comment by ariehead** [comment] 2017-07-14 13:15
Same issue as I adressed: issue #1516

**Comment by ariehead** [comment] 2017-07-17 07:18
Don´t know what happened but it is solved !
Please close this issue ..

**Comment by minj** [comment] 2017-07-18 17:41
sorry, I do not speak French

duplicate of #1516

**Closed by minj** 2017-07-18 17:41 UTC
