### ISSUE TITLE
suggestion, team goals in player list view

### ISSUE THREAD

**Issue by albertilius** [minj/foxtrick#1512] opened 2017-06-07 07:07 UTC
Hi

It is possible to have an avaiable column in players table (that is veeery useful!) that you can see the Goals each player has scored in YOUR TEAM, as you can see in the individual player page... Right now, in the players list, you can only see the goals of the player in the current season or in his career, but not the goals he has scored for your team. It would be funnier =)

Thanks

**Comment by minj** [comment] 2017-07-18 17:32
duplicate of #1330

**Closed by minj** 2017-07-18 17:32 UTC
