### ISSUE TITLE
Transfer search shows no results

### ISSUE THREAD

**Issue by tgraham1961** [minj/foxtrick#1390] opened 2016-03-20 01:28 UTC
win7 home premium  SP1
Chrome 49.0.2623.87 m
foxtrick 0.16.1.1
executing a saved search in transfer list flashes the first page of results on screen then they disappear.
Does not do this in IE 11, does not do this when foxtrick is disabled in chrome.
cleared cache - no result.

**Comment by minj** [comment] 2016-03-20 01:31
https://github.com/minj/foxtrick/issues?utf8=%E2%9C%93&q=is%3Aissue+transfer
:frowning: 

duplicate of #1387

**Closed by minj** 2016-03-20 01:31 UTC
