### ISSUE TITLE
Match Prediction is not working

### ISSUE THREAD

**Issue by mattadiro** [minj/foxtrick#1519] opened 2017-07-16 17:31 UTC
Hi ...  I use Foxtrick a lot to calculate the match predictions , but some days ago is not operating , showing that I have 0 probabilities to win with any line up that I do. 
![hattrick00](https://user-images.githubusercontent.com/30216401/28249808-893d90c4-6a22-11e7-9b9a-23e9bb00ae58.png)
![hattrick01](https://user-images.githubusercontent.com/30216401/28249809-8f4e8a18-6a22-11e7-9268-f1a42e4c6f72.png)
Using the option stamina discount I do not get the tactical skills.

So I am really worry because is a great tool. 

this is not operating in any browser.

I attach some images to show you .

Thanks a lot .  Please fix it soon :) 👍

**Comment by ariehead** [comment] 2017-07-17 07:14
Same issue as #1515 #1516 #1518 

Don´t know what happened but it is solved !
Please close this issue ..

**Comment by minj** [comment] 2017-07-18 17:43
duplicate of #1516

**Closed by minj** 2017-07-18 17:43 UTC
