### ISSUE TITLE
Impossible to install Foxtrick

### ISSUE THREAD

**Issue by EnnemiPublicNumero1** [minj/foxtrick#1346] opened 2015-10-23 10:07 UTC
HI guys,

I use Foxtrick pretty often. Without it, Hattrick does not have the same interest for me.
I used to have the version 0.13 something, and it had not been working for the past few weeks.
So I decided to update it, that's when I saw that the latest version is the 0.16.
So I deleted the version I had, and tried to install version 0.16
But unfortunately it seems that Firefox is blocking the download of the addon. This is the message I get :
![sans titre](https://cloud.githubusercontent.com/assets/15246324/10689854/4c702008-797e-11e5-84b6-64a7412ec2ab.jpg)
It says I have a connexion problem which is ridiculous because I have full access to internet...
So it is currently impossible for me to install Foxtrick.
Can you please help ?

**Comment by minj** [comment] 2015-10-23 10:12
This looks like a typical Avast problem. Here's a possible solution:

------
**From:** LA-MJ
**PostID:** [15946817.9](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D15946817%26n%3D9%26v%3D0)
**To:** Everyone
**Re:** [15946817.1](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D15946817%26n%3D1%26v%3D0)
**Datetime:** 2015-04-17 13:07
**Message:**

**I cannot install Foxtrick in Firefox**
►Error: "The addon could not be downloaded because of a connection failure on www.foxtrick.org."

This may be caused by Avast anti-virus, which blocks installation of browser extensions. You may be able to work around by right-clicking to download the .xpi file, then dragging it into Firefox to install. If that fails, you may temporarily disable Avast anti-virus before installing the extension.

Information source: [(https://www.eff.org/privacybadger#connection-fa...)](https://www.eff.org/privacybadger#connection-failure)

**Comment by EnnemiPublicNumero1** [comment] 2015-10-23 14:55
First solution worked great, thanks for your reply :+1:

**Comment by minj** [comment] 2015-10-23 14:59
great, closing the bug then

**Closed by minj** 2015-10-23 14:59 UTC
Labels: bug, invalid, Platform-Firefox, Priority-Medium
