### ISSUE TITLE
Feature request: add goto link to every publicly accessible page

### ISSUE THREAD

**Issue by mindw0rm** [minj/foxtrick#1514] opened 2017-07-09 10:55 UTC
I suggest adding a go-link to the current page on every page that is publicly (i.e. for everyone logged in) accessible (example for a not accessible page: club finances). If deciding the accessibility is too much effort, a link on every page would be fine as well. 
These fancy links redirect you to the server where you are currently logged in. 
Klicking the link should copy the goto url to the clipboard. 

Structure of goto link: for page http(s)://wwwXY-or-stage.hattrick.org/some/url/path, the goto link has the form https://www.hattrick.org/goto.ashx?path=/some/url/path (better urlencoded: https://www.hattrick.org/goto.ashx?path=%2Fsome%2Furl%2Fpath).

Label could be "share link to this page" or something like that.

**Comment by minj** [comment] 2017-07-18 17:30
duplicate of #1447

**Closed** 2017-07-18 17:31 UTC
Labels: duplicate, feature, Priority-Low
