### ISSUE TITLE
Transfer market research result empty

### ISSUE THREAD

**Issue by Sistemlegend** [minj/foxtrick#1387] opened 2016-03-13 10:28 UTC
After a market research a can't see any player in the results view . 
If i disable foxtrick they all show . thi s appens boh on firefox and chrome (latest versions).
My language is Italian .

**Comment by minj** [comment] 2016-03-13 11:02
Duplicate of #1384

Already fixed, you can get it from https://www.foxtrick.org/download/beta if you wish

**Closed by minj** 2016-03-13 11:02 UTC
